name: push to web server

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
 deploy:
    name: deploy
    runs-on: web-server
    steps:
      - name: pull repository
        run: |
              cd /home/ubuntu/${{ github.event.repository.name }}
              git pull
      - name: docker build & run
        run: |
              cd /home/ubuntu/${{ github.event.repository.name }}
              sudo docker-compose up -d --build
      - name: list running docker containers
        run: |
              sudo docker ps