name: push to web server

on:
  release:
    types: [published]

jobs:
 deploy:
    name: deploy
    runs-on: web-server
    steps:
      - name: clone repository
        run: |
              cd /home/ubuntu/${{ github.event.repository.name }}
              git pull
      - name: docker build & run
        run: |
              cd /home/ubuntu/${{ github.event.repository.name }}
              sudo docker-compose up -d --build
      - name: list running docker containers
        run: |
              sudo docker ps